### ISSUE TITLE
`fix-python` target should also fix lint violations

### ISSUE THREAD

**Issue by gentooboontoo** [Kozea/MakeCitron#18]
Currently, `fix-python` only reformats source files (python and jinja2). It should also fix trivial lint violations to be consistent with errors reported by `lint-python` target.

- [x] add `$(RUFF) check --fix $(LINTED_PYTHON_DIRS)` to `fix-python` target
- [x] update target documentation comment: `fix-python: Fix python source format and lint violations`
- [x] both `v3-legacy` and `v5` branches should be updated

**Comment by SajedehAdelia** [comment]
I have created two PR #20  and #19 for this ticket.
