### ISSUE TITLE
Only lint staged files if any, otherwise lint all files

### ISSUE THREAD

**Issue by gentooboontoo** [Kozea/MakeCitron#6]
## Rationale

`pre-commi(t)` calls `lint`. Linting check all files even if not staged.

When committing, it is useless to lint already committed files and linting could also take a non-negligible time. But as principle of least surprise, manually calling `make lint` should lint all files because it is what is expected. Moreover, CI calling `make lint` expect all files are linted / checked.

This issue should fix this problem by being aware of current context (committing or not).

**Comment by alexandreNoens** [comment]
Closed by https://github.com/Kozea/MakeCitron/pull/7
